---
- hosts: all

  tasks:
    - include: tasks/downloads.yml tags=download
    - include: tasks/apps.yml tags=apps
    - include: tasks/github.yml tags=github
    - include: tasks/dotfiles.yml tags=dotfiles
